sudo: required
services:
    - docker
before_install: 
    - docker build -t miladsaliba/docker-react -f Dockerfile.dev . 

script: 
    - docker run miladsaliba/docker-react npm run test -- --coverage
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker_react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-170226911968"
    bucket_path: "docker_react"
    on:
        branch: master
    access_key_id: $aws_access_key
    secret_access_key:
        secure: $AWS_SECRET_KEY
    